services:

  database:
    image: bitnami/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: arc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data